# Site settings
title: Illusionist
description: 'Entrepreneur | Interest in future technologies | Atheist | Founder of AI blogging platform'
url: 'https://girishnayak12.github.io'
baseurl: 
#google_analytics: 'UA-86671472-1'
#disqus_shortname: 'video-cortex'

author:
  name: 'Girish Nayak'
  #email: josh@joshgerdes.com
  twitter_username: gireeshnayak
  #facebook_username: joshgerdes
  github_username:  girishnayak12
  linkedin_username:  in/girishnayak12

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
